apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:15.0
          ports:
          - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "12345"
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_DB
            value: "banco"

---
# Serviço para expor o banco de dados postgres
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
    - port: 5432
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: postgre
          image: otaviodioscanio/kube-news:{{TAG}}
          ports:
          - containerPort: 8080
          env:
          - name: DB_PASSWORD
            value: "12345"
          - name: DB_USERNAME
            value: "admin"
          - name: DB_DATABASE
            value: "banco"
          - name: DB_HOST
          # nome do service
            value: "postgre"

---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer